import streamlit as st

st.header("Morning Checklist")
st.write("")
st.write("Make sure all carts return carts and P3 carts are put away.")
st.write("P3RACK1A, P3RACK1B, P3RACK1C, P3RACK1D, P3RACK3, RTNCRT2, RTNCRT3, RTNPLT1, RTNFRONT")
st.write("FCRTN - these are all customer discrepancies, just needs to be adjusted out of stock")
st.write("Check ASN Folder - file anything outdated.")
st.write("Check Oustanding Transfer Receipts - file anything over 10 days if not filed already.")
st.write("")
st.header("End of Night Checklist")
st.write("")
st.write("Make sure all receiving carts are empty.")
st.write("RCVSMALL1, RCVSMALL2, RCVSMALL3, RCVSMALL4, RCVCRT1-24, RCVPLT1-59")
st.write("Post all receiving jobs.")
st.write("Run reports:")
st.write("  - Multiple Items in Bin")
st.write("  - Multiple locations per Item")
st.write("  - Missing Primary Locations")
st.write("  - CORE Mismatch")
st.write("  - NOBINs (new)")
st.write("  - Zero Qty Bins")
st.write("  - Bin Size Missmatch")
st.write("Check gateway for errors.")
